# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

bicgSparse <- function(A, b, nb_iter = 100L, err = 1e-15) {
    .Call('_HodgePaths_bicgSparse', PACKAGE = 'HodgePaths', A, b, nb_iter, err)
}

build_boundary_Cu <- function(filtration, sort_input = TRUE) {
    .Call('_HodgePaths_build_boundary_Cu', PACKAGE = 'HodgePaths', filtration, sort_input)
}

cgSparse <- function(A, b, iguess, nb_iter = 100L, err = 1e-15) {
    .Call('_HodgePaths_cgSparse', PACKAGE = 'HodgePaths', A, b, iguess, nb_iter, err)
}

minres <- function(A, b, nb_iter = 100L, err = 1e-15) {
    .Call('_HodgePaths_minres', PACKAGE = 'HodgePaths', A, b, nb_iter, err)
}

